version: 2.1

description: >
  This orb is a wrapper for the Styra cli tool. The tool allows to run policy checks on your kubernetes configuration files (yaml).
display:
  home_url: https://styra.com
  source_url: https://github.com/styrainc/styra-cli-orb

examples:
  check-system-policies:
    usage:
      version: 2.1
      
      orbs:
        styra-orb: styra/cli

        workflows:
          version: 2.1
          check-workflow:
            jobs:
            - styra-orb/styra-policy-check
    
executors:
  cli:
    docker:
      - image: styra/cli

commands:
  policy-check:
    description: Configures and runs the Styra cli 
    parameters:
      api_token:
        description: Styra API Token for your styra account
        type: env_var_name
      tenant:
        description: Styra name of your styra account (e.g. test.styra.com)
        type: env_var_name
    steps:
      - run: styra-cli configure -i ${<< parameters.tenant >>} -t ${<< parameters.api_token >>}
      - run: |
          mkdir test
          styra-cli validate check-local -r . -o test/results.json
      - run:
           when: on_fail
           command: cat test/results.json
      - store_test_results:
           path: test
      - store_artifacts:
           path: test

jobs:
  styra-policy-check:
    executor: cli
    steps:
      - checkout        # check out the code in the project directory
      - policy-check:   # run the policy check cmd
          api_token : STYRA_TOKEN
          tenant: STYRA_TENANT
